/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A libcurl easy handle with RAII cleanup.
 *
 * When this object is garbage collected, `curl_easy_cleanup` is called
 * automatically, freeing all associated resources.
 */
export declare class Curl {
  /**
   * Create a new Curl handle.
   *
   * Equivalent to `curl_easy_init()`.
   */
  constructor()
  /**
   * Set a string option on the curl handle.
   *
   * @param opt - The CurlOpt option to set
   * @param value - The string value
   */
  setoptStr(opt: CurlOpt, value: string): void
  /**
   * Set a long/boolean option on the curl handle.
   *
   * @param opt - The CurlOpt option to set
   * @param value - The numeric value (0/1 for booleans)
   */
  setoptLong(opt: CurlOpt, value: number): void
  /**
   * Set a string-list option on the curl handle.
   *
   * @param opt - The CurlOpt option to set (HttpHeader, ProxyHeader, Resolve)
   * @param values - Array of strings
   */
  setoptList(opt: CurlOpt, values: Array<string>): void
  /**
   * Get info from the curl handle after a transfer.
   *
   * Returns a JSON-compatible value (number, string, or null).
   *
   * @param info - The CurlInfo key to retrieve
   */
  getinfo(info: CurlInfo): number | string
  /**
   * Enable the in-memory cookie engine.
   *
   * Must be called before perform to enable cookie persistence.
   */
  enableCookies(): void
  /** Get all cookies from the cookie engine as Netscape-format strings. */
  getCookies(): Array<string>
  /**
   * Add a cookie to the cookie engine in Netscape format.
   *
   * Format: ".domain.com\tTRUE\t/\tFALSE\t0\tname\tvalue"
   */
  addCookie(cookieLine: string): void
  /** Clear all cookies from the cookie engine. */
  clearCookies(): void
  /**
   * Set browser impersonation using a BrowserType enum value.
   *
   * This configures the TLS ClientHello, HTTP/2 settings, and default headers
   * to match the specified browser version.
   *
   * @param browser - The BrowserType to impersonate
   * @param default_headers - Whether to apply default browser headers (default: true)
   */
  impersonate(browser: BrowserType, defaultHeaders?: boolean | undefined | null): void
  /**
   * Set browser impersonation using a raw string target.
   *
   * For advanced use cases where a custom or newer browser identifier is needed.
   *
   * @param target - The browser target string (e.g., "chrome131.0")
   * @param default_headers - Whether to apply default browser headers (default: true)
   */
  impersonateStr(target: string, defaultHeaders?: boolean | undefined | null): void
  /**
   * Perform a synchronous HTTP request.
   *
   * Executes the request and returns the body, headers, and status code.
   * The curl handle is blocked until the response is fully received.
   *
   * @returns PerformResult with body (Buffer), headers (string), statusCode
   */
  perform(): PerformResult
  /**
   * Perform an asynchronous HTTP request.
   *
   * Duplicates the handle and runs `curl_easy_perform` on a libuv thread pool
   * worker. The Node.js event loop is NOT blocked during the request.
   *
   * @returns Promise<PerformResult>
   */
  performAsync(): Promise<unknown>
  /**
   * Connect to a WebSocket server.
   *
   * Sets CONNECT_ONLY=2 and performs the upgrade handshake.
   * After this returns, use wsSend/wsRecv for messaging.
   */
  wsConnect(): void
  /**
   * Send data on a WebSocket connection.
   *
   * @param data - Binary data to send
   * @param flags - CURLWS_TEXT (1) or CURLWS_BINARY (2) or CURLWS_CLOSE (8)
   */
  wsSend(data: Buffer, flags: number): void
  /**
   * Receive one frame from a WebSocket connection.
   *
   * Returns { data: Buffer, flags: number } or null if connection closed.
   * Call this in a loop to read all incoming messages.
   */
  wsRecv(bufferSize?: number | undefined | null): WsFrame | null
  /** Reset all options to defaults, allowing handle reuse. */
  reset(): void
  /** Clone this curl handle with all its options. */
  duplicate(): Curl
  /** Get a human-readable error description for the last error code. */
  strerror(code: number): string
}

/**
 * Supported browser impersonation targets.
 *
 * Each variant maps to a specific browser version string accepted by
 * `curl_easy_impersonate()`.
 */
export declare const enum BrowserType {
  /** Chrome 99 (Windows 10) */
  Chrome99 = 'chrome99',
  /** Chrome 100 (Windows 10) */
  Chrome100 = 'chrome100',
  /** Chrome 101 (Windows 10) */
  Chrome101 = 'chrome101',
  /** Chrome 104 (Windows 10) */
  Chrome104 = 'chrome104',
  /** Chrome 107 (Windows 10) */
  Chrome107 = 'chrome107',
  /** Chrome 110 (Windows 10) */
  Chrome110 = 'chrome110',
  /** Chrome 116 (Windows 10) */
  Chrome116 = 'chrome116',
  /** Chrome 99 (Android 12, Pixel 6) */
  Chrome99Android = 'chrome99_android',
  /** Edge 99 (Windows 10) */
  Edge99 = 'edge99',
  /** Edge 101 (Windows 10) */
  Edge101 = 'edge101',
  /** Safari 15.3 (macOS) */
  Safari15_3 = 'safari15_3',
  /** Safari 15.5 (macOS) */
  Safari15_5 = 'safari15_5'
}

/**
 * Info keys for `Curl.getinfo()`.
 *
 * Each variant maps to a specific `CURLINFO_*` constant from libcurl.
 * The return type (string, long, double) is determined by the variant.
 */
export declare const enum CurlInfo {
  /** The last HTTP response code. */
  ResponseCode = 0,
  /** Total time for the transfer in seconds. */
  TotalTime = 1,
  /** Time for name resolving in seconds. */
  NameLookupTime = 2,
  /** Time to connect in seconds. */
  ConnectTime = 3,
  /** Time to SSL/TLS handshake in seconds. */
  AppConnectTime = 4,
  /** Time until the first byte was received in seconds. */
  StartTransferTime = 5,
  /** The effective URL that was fetched (after redirects). */
  EffectiveUrl = 6
}

/**
 * Options for `Curl.setopt()`.
 *
 * Each variant maps to a specific `CURLOPT_*` constant from libcurl.
 * The option type (string, long, slist) is determined by the variant.
 */
export declare const enum CurlOpt {
  /** Set the URL to work with. */
  Url = 0,
  /** Set custom request method (GET, POST, PUT, DELETE, etc.) */
  CustomRequest = 1,
  /** Set the POST data body. */
  PostFields = 2,
  /** Set the User-Agent header. */
  UserAgent = 3,
  /** Set the Referer header. */
  Referer = 4,
  /** Set a cookie string ("name=value; name2=value2"). */
  Cookie = 5,
  /** Set the file to read cookies from. */
  CookieFile = 6,
  /** Set the file to write cookies to. */
  CookieJar = 7,
  /** Set proxy URL. */
  Proxy = 8,
  /** Set username for authentication. */
  Username = 9,
  /** Set password for authentication. */
  Password = 10,
  /** Set TLS cipher list (e.g., "ECDHE-RSA-AES128-GCM-SHA256:...") */
  SslCipherList = 11,
  /** Set TLS 1.3 ciphersuites (e.g., "TLS_AES_128_GCM_SHA256:...") */
  Tls13Ciphers = 12,
  /** Set elliptic curves (e.g., "X25519:P-256:P-384") */
  SslEcCurves = 13,
  /** Set TLS signature hash algorithms (e.g., "ecdsa_secp256r1_sha256,...") */
  SslSigHashAlgs = 14,
  /** Set certificate compression algorithms (e.g., "brotli") */
  SslCertCompression = 15,
  /** HTTP/2 pseudo-headers order (e.g., "masp" for :method, :authority, :scheme, :path) */
  Http2PseudoHeadersOrder = 16,
  /** HTTP/2 SETTINGS frame values (e.g., "1:65536;2:0;3:1000;4:6291456;6:262144") */
  Http2Settings = 17,
  /** HTTP/2 stream initial parameters (e.g., "3:0:0:201") */
  Http2Streams = 18,
  /** Follow HTTP redirects (0 or 1). */
  FollowLocation = 19,
  /** Maximum number of redirects to follow. */
  MaxRedirs = 20,
  /** Timeout in milliseconds for the entire transfer. */
  TimeoutMs = 21,
  /** Timeout in milliseconds for the connection phase. */
  ConnectTimeoutMs = 22,
  /** Verify the SSL peer certificate (0 or 1). */
  SslVerifyPeer = 23,
  /** Verify the SSL host (0 or 2). */
  SslVerifyHost = 24,
  /** Enable POST method (0 or 1). */
  Post = 25,
  /** Set POST data size. */
  PostFieldSize = 26,
  /** Set port number. */
  Port = 27,
  /** Enable HTTP proxy tunneling (0 or 1). */
  HttpProxyTunnel = 28,
  /** Enable upload mode (0 or 1). */
  Upload = 29,
  /** Enable TLS ALPS extension (0 or 1). */
  SslEnableAlps = 30,
  /** Enable/disable TLS session tickets (0 or 1). */
  SslEnableTicket = 31,
  /** Enable TLS extension permutation (0 or 1). */
  SslPermuteExtensions = 32,
  /** HTTP version to use (e.g., 4 for HTTP/2). */
  HttpVersion = 33,
  /** HTTP/2 initial window update value. */
  Http2WindowUpdate = 34,
  /** HTTP/2 stream weight (1-256). */
  StreamWeight = 35,
  /** Set custom HTTP headers. */
  HttpHeader = 36,
  /** Set proxy-specific headers. */
  ProxyHeader = 37,
  /** Set custom DNS resolve mappings. */
  Resolve = 38
}

/** Returns the libcurl version string from the linked curl-impersonate library. */
export declare function curlVersion(): string

/**
 * A minimal hello function to verify the napi binding works correctly.
 * This will be replaced with actual curl bindings in subsequent stories.
 */
export declare function hello(): string

/** Returns the version of the native module. */
export declare function nativeVersion(): string

/** Result of a synchronous `Curl.perform()` call. */
export interface PerformResult {
  /** Response body as a Buffer. */
  body: Buffer
  /** Raw response headers as a string (each header line separated by \r
  ). */
  headers: string
  /** HTTP status code (e.g., 200, 404, 500). */
  statusCode: number
  /** The effective URL after any redirects. */
  effectiveUrl: string
  /** DNS resolution time in milliseconds. */
  dnsTimeMs: number
  /** TCP connection time in milliseconds. */
  connectTimeMs: number
  /** TLS handshake time in milliseconds. */
  tlsTimeMs: number
  /** Total request time in milliseconds. */
  totalTimeMs: number
}

/** WebSocket frame received from wsRecv(). */
export interface WsFrame {
  /** Frame payload data. */
  data: Buffer
  /** Frame flags (CURLWS_TEXT=1, CURLWS_BINARY=2, CURLWS_CLOSE=8). */
  flags: number
}
